name: "publish"
on:
  push:
    # tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  docker:
    runs-on: ubuntu-22.04
    timeout-minutes: 3600
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract files from mermaid-live-editor
        run: |
          # 拉取镜像（只在 amd64 平台运行）
          docker pull ghcr.io/mermaid-js/mermaid-live-editor
          # 创建临时容器并复制文件
          docker create --name temp-container ghcr.io/mermaid-js/mermaid-live-editor
          docker cp temp-container:/usr/share/nginx/html ./static-files
          docker rm temp-container
          # 验证复制的文件
          ls -la ./static-files
          echo "Files extracted successfully:"
          find ./static-files -type f | head -10
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            vicanso/mermaid-editor
          tags: |
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}